[package]
name = "taichi-sys"
version = "0.1.0"
edition = "2021"
links = "taichi_c_api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"

[build-dependencies]
dotenvy = "0.15"
